# Generated by Django 5.0.1 on 2024-01-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('topic', models.CharField(choices=[('Project', 'Project'), ('Blog', 'Blog'), ('UI/UX Project', 'UI/UX Project'), ('Certificate', 'Certificate'), ('Skills', 'Skills')], max_length=100)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('intro', models.TextField()),
                ('content', models.TextField()),
                ('skills', models.TextField()),
                ('collab_Mail', models.TextField()),
                ('certifiedBy', models.TextField()),
            ],
        ),
    ]
