# Generated by Django 5.0.1 on 2024-01-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_contactus_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus_form',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
