# Generated by Django 5.0.1 on 2024-01-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_contactus_form_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_form',
            name='topic',
            field=models.CharField(choices=[('Project', 'Project'), ('Blog', 'Blog'), ('UI/UX Project', 'UI/UX Project'), ('Certificate', 'Certificate'), ('Skills', 'Skills'), ('UnityProject', 'UnityProject')], max_length=100),
        ),
    ]
